### ISSUE TITLE
Two left legs? gait9dof18musc_Thelen_BigSpheres.osim

### ISSUE THREAD

**Issue by hagrid67** [stanfordnmbl/osim-rl#75]
It looks like the skeleton model gait9dof18musc_Thelen_BigSpheres.osim has two left legs, with muscles in the right leg attaching to empty space.  Could this affect the dynamics?

**Comment by hagrid67** [comment]
![image](https://user-images.githubusercontent.com/9860840/30712248-48ab1e94-9f03-11e7-8054-3c1343983664.png)
I think you can see it in this image.

**Comment by hagrid67** [comment]
![image](https://user-images.githubusercontent.com/9860840/30712387-c6b76ba8-9f03-11e7-99fa-e14c0413edc0.png)
Here's another from the opensim editor app on windows, from behind.  You can see the femur, tibia and fibia are all duplicated without left/right reflection.

**Comment by hagrid67** [comment]
![image](https://user-images.githubusercontent.com/9860840/30712717-d7f864ca-9f04-11e7-9942-40c48790d69a.png)
Not a problem in the file gait10dof18musc.osim, from the Opensim3.3 package.

**Comment by ViktorM** [comment]
Very interesting finding! It's quit weird and should be fixed I think as soon as possible if it confirms.

**Comment by syllogismos** [comment]
I tried looking into the gaid9dof18musc.osim xml definition file..

This is my understanding, so each `Body` tag defines each muscle/bone, and with in the body tag there is `VisibleObject` and `DisplayGeometry` tag that loads a `.vtp` file that defines the shape? of that muscle? Anyway.. 

So `femur_r` is loded from `femur.vtp` file here https://github.com/stanfordnmbl/osim-rl/blob/fbdc442f755e5e77fc44b072a934a015ab5eb67b/osim/models/gait9dof18musc.osim#L255-L261

And `femur_l` is loaded from `l_femur.vtp` file here https://github.com/stanfordnmbl/osim-rl/blob/fbdc442f755e5e77fc44b072a934a015ab5eb67b/osim/models/gait9dof18musc.osim#L747


 and I did a diff on both `femur.vtp` and `l_femur.vtp` and I found both the files to be same. But other right and left body parts like foot and etc have some difference. You can find these geometries in `https://github.com/stanfordnmbl/osim-rl/tree/master/osim/models/Geometry` this folder.

Maybe here you are supposed to make use of the transform tag just few lines after loading the `.vtp` file to make it a mirror image

and from wikipedia femur turned out to be this part ![femur](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Femur_-_anterior_view2.png/1920px-Femur_-_anterior_view2.png)

**Comment by kidzik** [comment]
Geometry files (vtp) are only for visualization so they don't affect dynamics. Nevertheless, of course, it makes sense to do it right. We will fix it in the next release. Thanks for reporting!

**Comment by AdamStelmaszczyk** [comment]
@kidzik Is 1.5 release going ok, when can we expect it? Mostly interested in https://github.com/stanfordnmbl/osim-rl/issues/64...

**Comment by hagrid67** [comment]
![image](https://user-images.githubusercontent.com/9860840/31241146-e7f5be8a-a9fa-11e7-805a-f5ec5f82f017.png)
Hi Łukasz - I see you've fixed the femur but I think the right tibia/fibula is still wrong.  But at least now the muscle attachments look better.  (Apart from the missing patella, which I understand is deliberate)
